
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Signpage from "./components/sign/sign";
import Navbar from "./components/nav";
import Footer from "./components/footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Electricart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
        {children}
            <Navbar></Navbar>
           <Signpage></Signpage>

            <Footer></Footer>
        
    
      </body>

    </html>
  );
}
